name: AccentureWorkshop

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      # Step 3 - Add tests and linting here.
      - name: Tests
        run: npm test
      - name: Run typescript lint and format check
        run: npm run lint:ts
      - name: Run styles lint and format check
        run: npm run lint:css
      - name: Hello
        run: echo "Hello, $FIRST_Name, ${{secrets.PASSWORD}}"
        env:
          FIRST_Name: Trond
      - name: Send email
        uses: dawidd6/action-send-mail@v3.5.0
      - name: Profile Readme Development Stats
        uses: anmol098/waka-readme-stats@V3


    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      # Step 2: Add deploy to Github pages here! Hot tip - The solution is in the Readme
      - name: Build
        run: npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
      
